### PR TITLE
Blog: Pull requests are the new design handoffs

### PR DESCRIPTION
**Pull request by johnson-brad**
@featurepeek/blog/pull-requests-are-the-new-design-handoffs/

### CODE REVIEW

**Review by jasonbarry — COMMENTED** [review]
> This has led to a new class of “full-stack designers.”

Yep, I agree with this. Framer [wrote a book](https://www.framer.com/books/framer-guide-to-react/) that woos designers to the React ecosystem. 

<details><summary>Browser metadata</summary>


    Path:          /blog/pull-requests-are-the-new-design-handoffs/
    Browser:       Safari 13.1.2 on Mac OS 10.14.6
    Viewport:      1282 x 714 @2x
    Language:      en-us

    
</details>

[View on FeaturePeek](https://peek.run/ppnh31ez) | [Mark as Resolved](https://dashboard.featurepeek.com/resolve/ppnh31ez/g3qcop/resolved)

**Review by jasonbarry — COMMENTED** [review]
> but there are also some smaller startups like Loom, Clubhouse, and others making moves in the team communication space.

I'd replace this instance of Clubhouse (since the other Clubhouse is mentioned below) with a shout-out to our friends at [Tandem](http://tandem.chat).

<details><summary>Browser metadata</summary>


    Path:          /blog/pull-requests-are-the-new-design-handoffs/
    Browser:       Safari 13.1.2 on Mac OS 10.14.6
    Viewport:      1282 x 714 @2x
    Language:      en-us

    
</details>

[View on FeaturePeek](https://peek.run/ppnh31ez) | [Mark as Resolved](https://dashboard.featurepeek.com/resolve/ppnh31ez/m5ecel/resolved)

**Review by jasonbarry — COMMENTED** [review]
> GitHub, and to somewhat lesser degrees, GitLab, npm, and others are the de facto public forums for software collaboration.  

I'd replace npm with [BitBucket](https://bitbucket.org) here – npm is more of a package registry (like an index of compiled, versioned, distribution-ready builds) rather than VCS like GitHub and friends.

<details><summary>Browser metadata</summary>


    Path:          /blog/pull-requests-are-the-new-design-handoffs/
    Browser:       Safari 13.1.2 on Mac OS 10.14.6
    Viewport:      1282 x 714 @2x
    Language:      en-us

    
</details>

[View on FeaturePeek](https://peek.run/ppnh31ez) | [Mark as Resolved](https://dashboard.featurepeek.com/resolve/ppnh31ez/kelc8z/resolved)

**Review by jasonbarry — COMMENTED** [review]
> For example, if you’re a Netlify user, they have a perfectly cromulent deploy preview tool.

image

hehe :-P placeholder adjective? 

<details><summary>Browser metadata</summary>


    Path:          /blog/pull-requests-are-the-new-design-handoffs/
    Browser:       Safari 13.1.2 on Mac OS 10.14.6
    Viewport:      1282 x 714 @2x
    Language:      en-us

    
</details>

[View on FeaturePeek](https://peek.run/ppnh31ez) | [Mark as Resolved](https://dashboard.featurepeek.com/resolve/ppnh31ez/13rc44/resolved)

**Review by johnson-brad — COMMENTED** [review]
"Cromulent" is on the Merriam-Webster "Words We're Watching" and I'm doing my part to advocate for its inclusion. 😇 Intentional use, but I can flip it out with another word if you think best haha.

<details><summary>Browser metadata</summary>


    Path:          /blog
    Browser:       Chrome 85.0.4183.102 on Mac OS 10.15.6
    Viewport:      1440 x 686 @2x
    Language:      en-US

    
</details>

[View on FeaturePeek](https://peek.run/ppnh31ez) | [Mark as Resolved](https://dashboard.featurepeek.com/resolve/ppnh31ez/3drcpj/resolved)

**Pull request merged**
